app = "tgexpensesbot"

[build]
  builder = ""

[env]
  PYTHONUNBUFFERED = "1"

[checks]
  [checks.disable]
    grace_period = "30s"
    interval = "1m"
    method = "tcp"
    path = "/"
    port = 80
    timeout = "2s"
