app = "tgexpensesbot"

[build]
  # Empty builder ensures Fly uses your Dockerfile instead of a buildpack
  builder = ""

[env]
  PYTHONUNBUFFERED = "1"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
